meta_product_name: "Upf Project"
meta_title: "Upf Project"
meta_description: "Plateforme de cours et de gestion de projet du parcours LSPI"
meta_image: "logo.png" # should exist in `app/assets/images/`
